version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    networks:
      - my_network
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  
  inventory:
    build:
      context: ./inventory
    container_name: inventory_service
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:rootpassword@mysql_container:3306/mydatabase
    networks:
      - my_network
    ports:
      - "5001:5001"
    depends_on:
      mysql:
        condition: service_healthy

  customers:
    build:
      context: ./customers
    container_name: customers_service
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:rootpassword@mysql_container:3306/mydatabase
    networks:
      - my_network
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy

  sales:
    build:
      context: ./sales
    container_name: sales_service
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:rootpassword@mysql_container:3306/mydatabase
    networks:
      - my_network
    ports:
      - "5002:5000"
    depends_on:
      mysql:
        condition: service_healthy

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
